import {CONFIG} from '../config.js';
import {salvarAuditoria,obterDashboard} from '../api.js';
const C=[['avaliacaoClinica','Avaliação clínica adequada'],['sinaisVitais','Sinais vitais registrados'],['causaOrganica','Causa orgânica investigada quando indicada'],['classificacaoRisco','Classificação de risco registrada'],['riscoSuicida','Risco suicida avaliado quando indicado'],['manejo','Manejo conforme protocolo'],['contencao','Contenção conforme protocolo quando utilizada'],['encaminhamento','Encaminhamento adequado'],['planoAlta','Plano de cuidado na alta quando aplicável'],['notificacao','Notificação realizada quando aplicável']];
const pct=v=>v===null||v===undefined?'—':(v*100).toFixed(1)+'%';
export function renderAuditoria(){return `<section class='card'><h2>Auditoria de adesão ao protocolo</h2><p>A auditoria passa a ter uma função objetiva: medir se o manejo registrado no prontuário está aderente ao protocolo municipal e identificar onde estão as não conformidades.</p><label>Unidade / visão dos resultados</label><select id='auditEscopo'>${CONFIG.ESCOPOS.map(x=>`<option>${x}</option>`).join('')}</select><div id='auditResumo' class='muted'>Carregando indicadores...</div></section>
<section class='card'><h3>Auditar prontuário</h3><div class='banner'>Este módulo contém <strong>Prontuário/Código</strong>. Não é armazenado offline nem exibido nos indicadores.</div><form id='formAuditoria'><label>Data da auditoria</label><input type='date' name='data' required><label>UPA</label><select name='upa'>${CONFIG.UPAS.map(x=>`<option>${x}</option>`).join('')}</select><label>Prontuário/Código</label><input name='prontuario' autocomplete='off' required><label>Tipo de crise</label><select name='tipo'><option>Crise ansiosa</option><option>Agitação psicomotora</option><option>Tentativa de suicídio</option><option>Outros</option></select><fieldset><legend>Critérios de adesão</legend>${C.map(([n,l])=>`<div class='choice-row'><span>${l}</span>${['Sim','Não','N/A'].map(v=>`<label><input type='radio' name='${n}' value='${v}' required> ${v}</label>`).join('')}</div>`).join('')}</fieldset><label>Não conformidades / observações</label><textarea name='observacoes'></textarea><div id='scoreBox' class='card'><strong>Adesão deste prontuário: —</strong></div><button class='primary' type='submit'>Salvar auditoria</button></form></section>`}
export async function bindAuditoria(showToast){
  const f=document.querySelector('#formAuditoria'),box=document.querySelector('#scoreBox'),resumo=document.querySelector('#auditResumo'),sel=document.querySelector('#auditEscopo');
  const calc=()=>{let a=0,s=0;C.forEach(([n])=>{const x=f.querySelector(`input[name='${n}']:checked`);if(x&&x.value!=='N/A'){a++;if(x.value==='Sim')s++}});const p=a?s/a:null;box.innerHTML=`<strong>Adesão deste prontuário: ${p===null?'—':(p*100).toFixed(1)+'%'}</strong>`;return p};
  f.addEventListener('change',calc);
  f.addEventListener('submit',async e=>{e.preventDefault();if(!navigator.onLine){showToast('Auditoria bloqueada offline por conter código de prontuário.');return}const d=Object.fromEntries(new FormData(f));d.assertividade=calc();await salvarAuditoria(d);showToast('Auditoria registrada.');f.reset();calc();await load()});
  let data=null;
  const draw=()=>{const a=data?.unidades?.[sel.value]?.auditoria||{};const crit=Object.entries(a.criterios||{}).map(([k,v])=>`<tr><td>${k}</td><td>${v.nao||0}</td><td>${pct(v.adesao)}</td></tr>`).join('');resumo.innerHTML=`<div class='kpis'><div class='kpi'><b>${a.totalAuditorias||0}</b><span>Prontuários auditados</span></div><div class='kpi'><b>${pct(a.assertividade)}</b><span>Adesão global</span></div><div class='kpi'><b>${a.naoConformidades||0}</b><span>Não conformidades</span></div></div><h3>Pontos de atenção</h3><div class='table-wrap'><table><thead><tr><th>Critério</th><th>Não conformidades</th><th>Adesão</th></tr></thead><tbody>${crit||'<tr><td colspan="3">Sem auditorias</td></tr>'}</tbody></table></div>`};
  const load=async()=>{try{data=(await obterDashboard()).data;draw()}catch(e){resumo.textContent=e.message}};sel.onchange=draw;await load();
}
